#!/usr/bin/python

import sys, re, string
import ConfigParser

#################### SETUP VARS
BASE_DIR= "/home/werner/oss/geda/spicelib/"
PARTDB_DIR = BASE_DIR + "indexfiles/"
SYMBOL_DIR = BASE_DIR + "symbol_templates/"

#################### FUNCTIONS
def list_parts(filename):
    lines = open(PARTDB_DIR + filename, "rt").readlines()
    parts = []
    for l in lines:
        l = string.strip(l)
        if l == "":      ## ignore empty lines
            continue
        if l[0] == "#":  ## ignore comment lines
            continue
        if l[0] != "[":
            continue
        if l == "[GLOBAL]":
            continue

        tok = string.split(l[1:-1],",")
        print tok[0] + "_" + tok[1]

def symbol(filename, partname):
    ind = ConfigParser.ConfigParser()
    ind.read(PARTDB_DIR + filename)

    [partname, partid] = string.split(partname,"_")
    part = partname+ ","+partid

    symbol = ind.get(part, "symbol")
    symbol_template = string.Template(open(SYMBOL_DIR + symbol).read())

    repl = dict(ind.items(part))
    modeldir = ind.get("GLOBAL","MODELDIR")
    repl["file"] = BASE_DIR + modeldir + repl["file"]
    sym = symbol_template.safe_substitute(repl)
    print sym,

def log(x):
    open("gedaparts.log","at").write(str(x) + "\n")

#################### MAIN

#log(sys.argv)

if len(sys.argv) == 2: ## --> list command
    list_parts(sys.argv[1])
elif len(sys.argv) == 3:  ## --> part command
    symbol(sys.argv[1], sys.argv[2])

